version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: properties_db
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: backend_service
    restart: always
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/properties_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "35000:35000"
    networks:
      - my_network

networks:
  my_network:

volumes:
  db_data:
